version: "2"

services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432"

  pgbouncer:
    image: starefossen/pgbouncer:latest
    links:
      - postgres
    ports:
      - "127.0.0.1:6543:6543"
    volumes:
      - ./pgbouncer.ini:/pgbouncer.ini
