---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.17.1

executors:
  # This must match .promu.yml.
  golang:
    docker:
      - image: cimg/go:1.24

jobs:
  test:
    executor: golang

    steps:
      - prometheus/setup_environment
      - run: make
      - prometheus/store_artifact:
          file: pgbouncer_exporter

workflows:
  version: 2
  pgbouncer_exporter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - prometheus/build:
          name: build
          parallelism: 3
          promu_opts: "-p linux/amd64 -p windows/amd64 -p linux/arm64 -p darwin/amd64 -p darwin/arm64 -p linux/386"
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: /^(main|master|release-.*|.*build-all.*)$/
      - prometheus/build:
          name: build_all
          parallelism: 12
          filters:
            branches:
              only: /^(main|master|release-.*|.*build-all.*)$/
            tags:
              only: /^v.*/
      - prometheus/publish_master:
          context: org-context
          docker_hub_organization: prometheuscommunity
          quay_io_organization: prometheuscommunity
          requires:
            - test
            - build_all
          filters:
            branches:
              only: master
      - prometheus/publish_release:
          context: org-context
          docker_hub_organization: prometheuscommunity
          quay_io_organization: prometheuscommunity
          requires:
            - test
            - build_all
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
